(()=>{
'use strict';
const VER='746';
const root=new URL('.',location.href);const asset=name=>new URL(name,root).href+'?v='+VER;
function css(){let s=document.getElementById('v743-ui-style');if(!s){s=document.createElement('style');s.id='v743-ui-style';document.head.appendChild(s)}s.textContent=`
/* PRIMA: fill the white brand tile while preserving the complete logo */
.logo-box{background:#fff!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:0!important;min-height:76px!important;height:76px!important;overflow:hidden!important;border-radius:8px!important}
.logo-box img.v741-logo{display:block!important;visibility:visible!important;opacity:1!important;width:224px!important;max-width:none!important;height:72px!important;object-fit:contain!important;object-position:center!important;background:transparent!important;filter:none!important;box-shadow:none!important;transform:scale(1.58)!important;transform-origin:center!important}
.logo-box .v743-logo-fallback{display:none!important;color:#1169b6!important;font-size:36px!important;font-weight:950!important;font-style:italic!important}.logo-box.v743-logo-error img{display:none!important}.logo-box.v743-logo-error .v743-logo-fallback{display:block!important}
/* Fuel Stock orb: larger, centered under FT stock, still contained */
.stock-panel .stock-total{right:8px!important;bottom:8px!important;width:47%!important;text-align:center!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;pointer-events:none!important}
.stock-panel .stock-total>small{font-size:10px!important;line-height:14px!important;font-weight:950!important;color:#fff!important;margin-bottom:4px!important}
.stock-panel .stock-orb{width:76px!important;height:76px!important;min-width:76px!important;min-height:76px!important;border-radius:50%!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;box-sizing:border-box!important}
.stock-panel .stock-orb strong{font-size:16px!important;line-height:19px!important;font-weight:950!important;color:#fff!important}.stock-panel .stock-orb span{font-size:8px!important;line-height:11px!important;color:#fff!important;font-weight:800!important}
.unit-type-panel{overflow:hidden!important}.unit-type-panel .unit-types{height:128px!important;min-height:128px!important;display:grid!important;grid-template-columns:1fr 1fr!important;overflow:hidden!important}.unit-type-panel .unit-types>div{display:grid!important;grid-template-rows:18px 55px 21px 14px 16px!important;align-items:center!important;justify-items:center!important;min-width:0!important;padding:1px 7px!important;box-sizing:border-box!important;overflow:hidden!important}.unit-type-panel .unit-types>div:first-child{border-right:1px solid rgba(101,135,163,.45)!important}.unit-type-panel .unit-types>div>small{color:#d8e2ed!important;font-size:8px!important;line-height:18px!important;font-weight:900!important;white-space:nowrap!important}.unit-type-panel .unit-icon{height:55px!important;width:100%!important;display:flex!important;align-items:center!important;justify-content:center!important;overflow:hidden!important}.unit-type-panel .unit-icon img{display:block!important;object-fit:contain!important;margin:auto!important;filter:drop-shadow(0 4px 5px rgba(0,0,0,.38))!important}.unit-type-panel .unit-types>div:first-child .unit-icon img{max-width:108px!important;max-height:53px!important}.unit-type-panel .unit-types>div:nth-child(2) .unit-icon img{max-width:76px!important;max-height:52px!important}.unit-type-panel .unit-types strong{font-size:15px!important;line-height:21px!important;color:#fff!important;font-weight:900!important}.unit-type-panel .unit-types strong+span{font-size:8px!important;line-height:14px!important;color:#fff!important}.unit-type-panel .unit-types b{font-size:8.5px!important;line-height:16px!important;color:#fff!important;font-weight:900!important}
.shift-panel .shift-content{display:grid!important;grid-template-columns:154px minmax(0,1fr)!important;align-items:center!important;gap:12px!important;min-height:158px!important}.shift-panel .chart.donut{width:150px!important;height:150px!important;min-width:150px!important;min-height:150px!important;margin:auto!important}.shift-panel .shift-item small{font-size:10px!important;color:#fff!important;font-weight:900!important}.shift-panel .shift-item strong{font-size:14px!important;color:#fff!important;font-weight:900!important}
@media(max-width:1350px){.logo-box img.v741-logo{width:214px!important;height:69px!important;transform:scale(1.5)!important}.stock-panel .stock-orb{width:70px!important;height:70px!important;min-width:70px!important;min-height:70px!important}.stock-panel .stock-orb strong{font-size:15px!important}.shift-panel .shift-content{grid-template-columns:138px minmax(0,1fr)!important}.shift-panel .chart.donut{width:134px!important;height:134px!important;min-width:134px!important;min-height:134px!important}}
`}
function logo(){const box=document.querySelector('.logo-box');if(!box)return;let img=box.querySelector('img.v741-logo');if(!img){box.replaceChildren();img=document.createElement('img');img.className='v741-logo';img.alt='PRIMA - PT Prima Sarana Gemilang';img.loading='eager';box.appendChild(img)}const url=asset('prima-logo.png');if(img.dataset.src!==url){img.dataset.src=url;img.src=url}let fb=box.querySelector('.v743-logo-fallback');if(!fb){fb=document.createElement('span');fb.className='v743-logo-fallback';fb.textContent='PRIMA';box.appendChild(fb)}img.onload=()=>box.classList.remove('v743-logo-error');img.onerror=()=>box.classList.add('v743-logo-error')}
function icons(){const nodes=document.querySelectorAll('.unit-type-panel .unit-icon');if(nodes.length<2)return;[['excavator-icon.svg','Excavator Produksi'],['gears-icon.svg','General Support Gears']].forEach(([file,alt],i)=>{let img=nodes[i].querySelector('img.v743-unit-icon');if(!img){nodes[i].replaceChildren();img=document.createElement('img');img.className='v743-unit-icon';img.alt=alt;nodes[i].appendChild(img)}const url=asset(file);if(img.dataset.src!==url){img.dataset.src=url;img.src=url}})}
function categoryChart(){try{if(typeof state==='undefined'||!state.charts)return;const c=state.charts.cat;if(!c)return;c.options.layout=c.options.layout||{};c.options.layout.padding={top:4,right:118,bottom:2,left:0};c.options.scales=c.options.scales||{};c.options.scales.x=c.options.scales.x||{};const vals=(c.data?.datasets?.[0]?.data||[]).map(Number).filter(Number.isFinite),max=vals.length?Math.max(...vals):0;if(max>0){c.options.scales.x.suggestedMax=max*1.58;c.options.scales.x.max=undefined}const dl=c.options.plugins?.datalabels;if(dl){dl.anchor='end';dl.align='right';dl.clamp=true;dl.clip=false;dl.offset=6;dl.color='#fff';dl.font={...(dl.font||{}),size:8,weight:'800'}}const ds=c.data?.datasets?.[0];if(ds){ds.maxBarThickness=13;ds.barPercentage=.68;ds.categoryPercentage=.76}c.update('none')}catch(e){console.warn('category layout',e)}}
function shiftChart(){try{if(typeof state==='undefined'||!state.charts)return;const c=state.charts.shift;if(!c)return;c.options.maintainAspectRatio=false;c.options.cutout='64%';c.options.layout={padding:2};c.resize();c.update('none')}catch(e){}}
function apply(){css();logo();icons();categoryChart();shiftChart()}apply();[80,250,600,1200,2200].forEach(t=>setTimeout(apply,t));['dateFrom','dateTo','shiftFilter','categoryFilter','truckFilter','unitSearch'].forEach(id=>document.getElementById(id)?.addEventListener(id==='unitSearch'?'input':'change',()=>{setTimeout(apply,100);setTimeout(categoryChart,260)}));window.addEventListener('pageshow',apply);window.addEventListener('resize',()=>setTimeout(apply,120),{passive:true});
})();